# Generated by Django 5.1.1 on 2024-09-09 14:21

import django.utils.timezone
import post_app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.TextField()),
                ('post_image', models.ImageField(storage=post_app.storage.S3ImageStorage(), upload_to='post_images/')),
                ('content', models.TextField()),
                ('link', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
