# Generated by Django 5.1.1 on 2024-09-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_comment_like_replay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(max_length=300),
        ),
    ]
