# Generated by Django 5.1.1 on 2024-09-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_alter_post_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Replay',
        ),
    ]
