# Generated by Django 5.1.1 on 2024-09-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0006_replay'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Replay',
            new_name='Reply',
        ),
    ]
