# Generated by Django 5.1.1 on 2024-10-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0008_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
    ]
